spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/kotlin_db
    username: root
    password: Aubetoile787