spring:
  application:
    name: Kotlin Hibernate
    hikari:
      maximum-pool-size: 16
      auto-commit: false
      connection-timeout: 10000
      idle-timeout: 60000
      minimum-idle: 2
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
  liquibase:
    change-log: classpath:liquibase/changelog/changelog.xml
  data:
    neo4j:
      open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/kotlin_db?serverTimezone=UTC
    username: root
    password: Aubetoile787
    driver-class-name: com.mysql.cj.jdbc.Driver
